### ISSUE TITLE
Fatal Error when attempting to change visibility of settings button

### ISSUE THREAD

**Issue by OutbackCatgirl** [LeonSkills/FactorioMods#1]
![image](https://user-images.githubusercontent.com/61132755/216880897-7f796311-a082-455b-8641-b4251f49ac3d.png)

**Comment by PittusM7** [comment]
I get the same error when loading a save after updating from a previous version.
Last version I played on was 1.1.2.
1.2.2 is the first version which has this error.
The error still occurs in the current version (1.2.7).

**Error Message:**

The mod Rail Signal Planner (1.2.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RailSignalPlanner::on_configuration_changed
Can't destroy root element
stack traceback:
	[C]: in function 'destroy'
	__RailSignalPlanner__/gui/signal_tool_gui.lua:37: in function 'remove_button'
	__RailSignalPlanner__/gui/signal_tool_gui.lua:61: in function 'initialize_player'
	__RailSignalPlanner__/gui/signal_tool_gui.lua:70: in function <__RailSignalPlanner__/gui/signal_tool_gui.lua:68>

**Comment by LeonSkills** [comment]
Thank you for the report!
Apologies for the late response, apparently email notifications were off on this account.  

I have fixed this in 1.2.9
