### ISSUE TITLE
Rail Signal Planner unrecoverable error

### ISSUE THREAD

**Issue by romanrsr** [LeonSkills/FactorioMods#2]
![Sin título](https://github.com/user-attachments/assets/1dcc4c4b-5703-464b-854c-37d2afae4d80)

Game version 2.0.21

**Comment by Honsal** [comment]
exactly same error ocurred here

**Comment by Honsal** [comment]
Mods: https://pastebin.com/13MpiswQ

Mod Settings: https://file.io/J4CbjF7FqdqM

Related Blueprint: https://factoriobin.com/post/tmv2d9xibz7s-EXPIRES

**Comment by LeonSkills** [comment]
I know Wube is awesome for supporting legacy rails, but I can't guarantee they work. 
I've added support for them in 2.0.2 but haven't tested extensively, please let me know if they still don't work properly.

**Comment by LeonSkills** [comment]
I know Wube is awesome for supporting legacy rails, but I can't guarantee they work. 
I've added support for them in 2.0.2, please let me know if they still don't work properly
